const{ethers}=require("ethers");
const MABI=["function registerAI(string,string,address) returns (uint256)","function writeMemory(uint256,uint8,string,string,uint8) returns (uint256)","function writeMemoryBatch(uint256,uint8[],string[],string[],uint8[])","function sealMemory(uint256,uint256)","function grantAccess(uint256,uint256)","function revokeAccess(uint256,uint256)","function getAIProfile(uint256) view returns (string,string,address,uint256,uint256,bool)","function getMemory(uint256) view returns (uint256,uint256,uint8,string,string,uint256,uint8,bool)","function getAIMemoryIds(uint256,uint256,uint256) view returns (uint256[])","function totalAIs() view returns (uint256)","function totalMemories() view returns (uint256)","function walletToAiId(address) view returns (uint256)"];
const TABI=["function name() view returns (string)","function symbol() view returns (string)","function totalSupply() view returns (uint256)","function balanceOf(address) view returns (uint256)","function transfer(address,uint256) returns (bool)","function approve(address,uint256) returns (bool)"];
const IABI=["function createIdentity(string,string,string,address,string[]) returns (uint256)","function attestTrust(uint256,uint256,uint8,string)","function getIdentity(uint256) view returns (tuple(uint256,string,string,string,address,address,uint256,uint256,uint256,uint8))","function getCapabilities(uint256) view returns (string[])","function walletToIdentity(address) view returns (uint256)","function totalIdentities() view returns (uint256)"];
const NETS={mainnet:{rpc:"https://rpc.chainmemory.ai",contracts:{token:"0x7a50ed017E175Eb4549d3BDd7DBCF319F9f30160",memory:"0xe8E195ba416Fb25F4FC3d0E7908ff9e8666dbb4A",identity:"0xd76a4D858073F962AB0c84E12113d43E82Af51A7"}}};
const CATS=["DECISION","LEARNING","INTERACTION","STATE","ERROR","MILESTONE","CUSTOM"];
const CMAP={DECISION:0,LEARNING:1,INTERACTION:2,STATE:3,ERROR:4,MILESTONE:5,CUSTOM:6};
class AICHAIN{constructor(c={}){const n=NETS[c.network||"mainnet"];this.rpc=c.rpc||n.rpc;this.ct=c.contracts||n.contracts;this.pk=c.privateKey;this.p=null;this.s=null;this.token=null;this.mem=null;this.id=null;this.aiId=null;this.idId=null;this._r=false;}
async connect(){this.p=new ethers.JsonRpcProvider(this.rpc);if(this.pk)this.s=new ethers.Wallet(this.pk,this.p);else throw new Error("privateKey required");this.token=new ethers.Contract(this.ct.token,TABI,this.s);this.mem=new ethers.Contract(this.ct.memory,MABI,this.s);this.id=new ethers.Contract(this.ct.identity,IABI,this.s);const a=await this.s.getAddress();const e=await this.mem.walletToAiId(a);if(e>0n)this.aiId=Number(e);const ei=await this.id.walletToIdentity(a);if(ei>0n)this.idId=Number(ei);this._r=true;return{address:a,chainId:1337,aiId:this.aiId};}
async register(name,model){this._c();const a=await this.s.getAddress();const e=await this.mem.walletToAiId(a);if(e>0n){this.aiId=Number(e);return{aiId:this.aiId,alreadyRegistered:true};}const tx=await this.mem.registerAI(name,model,a);const r=await tx.wait();this.aiId=Number(await this.mem.totalAIs());return{aiId:this.aiId,txHash:r.hash};}
async createIdentity(name,model,ver,caps=[]){this._c();const a=await this.s.getAddress();const tx=await this.id.createIdentity(name,model,ver,a,caps);const r=await tx.wait();this.idId=Number(await this.id.totalIdentities());return{identityId:this.idId,txHash:r.hash};}
async remember(summary,opts={}){this._c();this._a();const cat=typeof opts.category==="string"?(CMAP[opts.category.toUpperCase()]??6):(opts.category??6);const imp=opts.importance??5;const h=opts.contentHash||ethers.keccak256(ethers.toUtf8Bytes(summary+Date.now()));const tx=await this.mem.writeMemory(this.aiId,cat,h,summary,imp);const r=await tx.wait();const mid=Number(await this.mem.totalMemories());if(opts.seal){const st=await this.mem.sealMemory(this.aiId,mid);await st.wait();}return{memoryId:mid,txHash:r.hash,sealed:!!opts.seal};}
async rememberBatch(mems){this._c();this._a();const cats=mems.map(m=>CMAP[m.category?.toUpperCase()]??6);const hs=mems.map(m=>m.contentHash||ethers.keccak256(ethers.toUtf8Bytes(m.summary+Date.now())));const ss=mems.map(m=>m.summary);const is=mems.map(m=>m.importance??5);const tx=await this.mem.writeMemoryBatch(this.aiId,cats,hs,ss,is);const r=await tx.wait();return{count:mems.length,txHash:r.hash};}
async seal(mid){this._c();this._a();const tx=await this.mem.sealMemory(this.aiId,mid);await tx.wait();return{sealed:true,memoryId:mid};}
async decision(s,i=7){return this.remember(s,{category:"DECISION",importance:i});}
async learned(s,i=5){return this.remember(s,{category:"LEARNING",importance:i});}
async interaction(s,i=3){return this.remember(s,{category:"INTERACTION",importance:i});}
async error(s,i=8){return this.remember(s,{category:"ERROR",importance:i});}
async milestone(s,i=10){return this.remember(s,{category:"MILESTONE",importance:i,seal:true});}
async recall(off=0,lim=20){this._c();this._a();const ids=await this.mem.getAIMemoryIds(this.aiId,off,lim);const r=[];for(const id of ids){const m=await this.mem.getMemory(id);r.push({id:Number(m[0]),category:CATS[Number(m[2])],contentHash:m[3],summary:m[4],timestamp:Number(m[5]),date:new Date(Number(m[5])*1000).toISOString(),importance:Number(m[6]),sealed:m[7]});}return r;}
async profile(){this._c();this._a();const p=await this.mem.getAIProfile(this.aiId);return{name:p[0],model:p[1],owner:p[2],memories:Number(p[3]),reputation:Number(p[4]),active:p[5]};}
async stats(){this._c();const b=await this.p.getBlockNumber();return{block:b,totalAIs:Number(await this.mem.totalAIs()),totalMemories:Number(await this.mem.totalMemories()),totalIdentities:Number(await this.id.totalIdentities()),supply:ethers.formatEther(await this.token.totalSupply())};}
async balance(addr){this._c();const a=addr||await this.s.getAddress();return ethers.formatEther(await this.token.balanceOf(a));}
async grantAccess(tid){this._a();const tx=await this.mem.grantAccess(this.aiId,tid);await tx.wait();}
async revokeAccess(tid){this._a();const tx=await this.mem.revokeAccess(this.aiId,tid);await tx.wait();}
async attestTrust(to,score,reason){this._c();const tx=await this.id.attestTrust(this.idId,to,score,reason);await tx.wait();}
_c(){if(!this._r)throw new Error("Call connect() first");}
_a(){if(!this.aiId)throw new Error("Call register() first");}}
module.exports={AICHAIN,CATS,CMAP,NETS};
